.\" Manpage for motd.
.\" Contact vi1i.petal@gmail.com for comments or help.
.TH man 1 "24 Oct 2018" "0.1.0" "motd man page"
.SH NAME
motd \- simple motd generator
.SH SYNOPSIS
motd
.SH DESCRIPTION
motd is a simple motd generator to be utilized with pam.
.SH OPTIONS
motd filename to modify with the motd info
.SH BUGS
No known bugs.
.SH AUTHOR
Vi1i Petal (vi1i.petal@gmail.com)
